adminPanel: Adminbereich
automation: Automatisierung
chart: Diagramme
configuration: Konfiguration
help:
  documentation: Dokumentation
  feedback: Feedback senden
  forum: Hilfe
  version: 'Version:'
module: Module
more: Mehr
namespace: Namensräume
noPageTitle: Kein Seitentitel
page: Seiten
publicPages: Öffentliche Seiten
userSettings:
  changePassword: Passwort ändern
  loggedInAs: Als {{user}} angemeldet
  logout: Abmelden
  profile: Profil
themes:
  labels:
    light: Hell
    dark: Dunkel
