editor:
  info:
    createdAt: Created at
    createdBy: Created by
    delete: Delete
    deletedAt: Deleted at
    enabled: Aktiviert
    id: ID
    name: Name
    title: Grundlegende Informationen
    undelete: Undelete
    updatedAt: Updated at
  new: New
  permissions: Permissions
  title:
    create: Create application
    edit: Edit application
  unify:
    config:
      description: Application configuration (JSON)
      label: Configuration
    listed: Listed
    logo:
      label: Logo
      description: Logo used in the application selector
      placeholder: Choose a logo or drop it here...
      reset: Reset
    name:
      description: Name used in the application selector
      label: Name
    pinned: Pinned
    title: Unify app selector
    url:
      description: Application URL
      label: URL
list:
  columns:
    actions: ""
    createdAt: Erstellt
    enabled: Aktiviert
    name: Name
    appListName: App selector name
    state: State
  export: Export
  rows:
    filters:
      deleted: Deleted
  filterForm:
    deleted:
      label: deleted applications
    excluded:
      label: Without
    exclusive:
      label: Only
    inclusive:
      label: Including
    query:
      label: Filter applications list
      placeholder: Filter applications by name
  loading: Loading applications
  new: New
  numFound: '{{count}} application found'
  numFound_plural: '{{count}} applications found'
  permissions: Permissions
  title: Applications
  yaml: YAML
  delete: Delete
  undelete: Undelete
